name: build-windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare resources
        shell: pwsh
        run: |
          if (-not (Test-Path media)) { New-Item -ItemType Directory -Path media | Out-Null }
          if (-not (Test-Path config.json)) { Set-Content -Path config.json -Value '{}' -Encoding UTF8 }

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Build exe with PyInstaller
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $args = @(
            'main.py',
            '--clean',
            '--noconfirm',
            '--windowed',
            '--onedir',
            '--name','WechatTool',
            '--add-data','media;media',
            '--add-data','config.json;.'
          )
          pyinstaller @args

      - name: Archive artifact
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if (Test-Path 'dist/WechatTool-win-x64.zip') { Remove-Item 'dist/WechatTool-win-x64.zip' -Force }
          Compress-Archive -Path 'dist/WechatTool/*' -DestinationPath 'dist/WechatTool-win-x64.zip' -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WechatTool-win-x64
          path: dist/WechatTool-win-x64.zip
