name: build-windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Build exe with PyInstaller
        shell: pwsh
        run: |
          pyinstaller main.py `
            --clean `
            --noconfirm `
            --windowed `
            --onedir `
            --name WechatTool `
            --add-data "media;media" `
            --add-data "config.json;."

      - name: Archive artifact
        shell: bash
        run: |
          cd dist
          7z a -tzip WechatTool-win-x64.zip WechatTool

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WechatTool-win-x64
          path: dist/WechatTool-win-x64.zip
